# Data overview

This notebook provides a data overview of the Formula 1 World Championship dataset.  

It examines the structure of each table, checks data quality, and verifies relationships between tables necessary for the Entity Relationship Diagram (ERD).

In [1]:
import sqlite3
import pandas as pd 
import numpy as np

In [2]:
conn = sqlite3.connect("db/formula1.db")

In [3]:
query = """ 
        SELECT * FROM sqlite_master
        """

pd.read_sql(query, conn)

,type,name,tbl_name,rootpage,sql
0,table,circuits,circuits,2,"CREATE TABLE ""circuits"" (\n""circuitId"" INTEGER..."
1,table,constructors,constructors,6,"CREATE TABLE ""constructors"" (\n""constructorId""..."
2,table,drivers,drivers,12,"CREATE TABLE ""drivers"" (\n""driverId"" INTEGER,\..."
3,table,races,races,35,"CREATE TABLE ""races"" (\n""raceId"" INTEGER,\n ""..."
4,table,results,results,76,"CREATE TABLE ""results"" (\n""resultId"" INTEGER,\..."

### circuits

In [4]:
query = """ 
        PRAGMA table_info(circuits)
        """

pd.read_sql(query, conn)

   cid        name     type  notnull dflt_value  pk
0    0   circuitId  INTEGER        0       None   0
1    1  circuitRef     TEXT        0       None   0
2    2        name     TEXT        0       None   0
3    3    location     TEXT        0       None   0
4    4     country     TEXT        0       None   0
5    5         lat     REAL        0       None   0
6    6         lng     REAL        0       None   0
7    7         alt  INTEGER        0       None   0
8    8         url     TEXT        0       None   0

In [5]:
pd.read_sql("SELECT * FROM circuits LIMIT 5", conn)

,circuitId,circuitRef,name,location,country,lat,lng,alt,url
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18,http://en.wikipedia.org/wiki/Sepang_Internatio...
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130,http://en.wikipedia.org/wiki/Istanbul_Park

In [6]:
query = """ 
        SELECT COUNT(*) AS total, COUNT(DISTINCT circuitId)
        FROM circuits
        """

pd.read_sql(query, conn)

   total  COUNT(DISTINCT circuitId)
0     77                         77

In [7]:
query = """ 
        SELECT *
        FROM circuits
        WHERE circuitId is NULL
        """

pd.read_sql(query, conn)

Empty DataFrame
Columns: [circuitId, circuitRef, name, location, country, lat, lng, alt, url]
Index: []

### constructors

In [8]:
query = """ 
        PRAGMA table_info(constructors)
        """

pd.read_sql(query, conn)

   cid            name     type  notnull dflt_value  pk
0    0   constructorId  INTEGER        0       None   0
1    1  constructorRef     TEXT        0       None   0
2    2            name     TEXT        0       None   0
3    3     nationality     TEXT        0       None   0
4    4             url     TEXT        0       None   0

In [9]:
pd.read_sql("SELECT * FROM constructors LIMIT 5", conn)

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso

In [10]:
query = """ 
        SELECT COUNT(*) AS total, COUNT(DISTINCT constructorId)
        FROM constructors
        """

pd.read_sql(query, conn)

   total  COUNT(DISTINCT constructorId)
0    212                            212

In [11]:
query = """ 
        SELECT *
        FROM constructors
        WHERE constructorId is NULL
        """

pd.read_sql(query, conn)

Empty DataFrame
Columns: [constructorId, constructorRef, name, nationality, url]
Index: []

### drivers

In [12]:
query = """ 
        PRAGMA table_info(drivers)
        """

pd.read_sql(query, conn)

   cid         name     type  notnull dflt_value  pk
0    0     driverId  INTEGER        0       None   0
1    1    driverRef     TEXT        0       None   0
2    2       number     TEXT        0       None   0
3    3         code     TEXT        0       None   0
4    4     forename     TEXT        0       None   0
5    5      surname     TEXT        0       None   0
6    6          dob     TEXT        0       None   0
7    7  nationality     TEXT        0       None   0
8    8          url     TEXT        0       None   0

In [13]:
pd.read_sql("SELECT * FROM drivers LIMIT 5", conn)

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [14]:
query = """ 
        SELECT COUNT(*) AS total, COUNT(DISTINCT driverId)
        FROM drivers
        """

pd.read_sql(query, conn)

   total  COUNT(DISTINCT driverId)
0    861                       861

In [15]:
query = """ 
        SELECT *
        FROM drivers
        WHERE driverId is NULL
        """

pd.read_sql(query, conn)

Empty DataFrame
Columns: [driverId, driverRef, number, code, forename, surname, dob, nationality, url]
Index: []

### races

In [16]:
query = """ 
        PRAGMA table_info(races)
        """

pd.read_sql(query, conn)

    cid         name     type  notnull dflt_value  pk
0     0       raceId  INTEGER        0       None   0
1     1         year  INTEGER        0       None   0
2     2        round  INTEGER        0       None   0
3     3    circuitId  INTEGER        0       None   0
4     4         name     TEXT        0       None   0
5     5         date     TEXT        0       None   0
6     6         time     TEXT        0       None   0
7     7          url     TEXT        0       None   0
8     8     fp1_date     TEXT        0       None   0
9     9     fp1_time     TEXT        0       None   0
10   10     fp2_date     TEXT        0       None   0
11   11     fp2_time     TEXT        0       None   0
12   12     fp3_date     TEXT        0       None   0
13   13     fp3_time     TEXT        0       None   0
14   14   quali_date     TEXT        0       None   0
15   15   quali_time     TEXT        0       None   0
16   16  sprint_date     TEXT        0       None   0
17   17  sprint_time     TEXT        0       None   0

In [17]:
pd.read_sql("SELECT * FROM races LIMIT 5", conn)

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [18]:
query = """ 
        SELECT COUNT(*) AS total, COUNT(DISTINCT raceId)
        FROM races
        """

pd.read_sql(query, conn)

   total  COUNT(DISTINCT raceId)
0   1125                    1125

In [19]:
query = """ 
        SELECT *
        FROM races
        WHERE raceId is NULL
        """

pd.read_sql(query, conn)

Empty DataFrame
Columns: [raceId, year, round, circuitId, name, date, time, url, fp1_date, fp1_time, fp2_date, fp2_time, fp3_date, fp3_time, quali_date, quali_time, sprint_date, sprint_time]
Index: []

### results

In [20]:
query = """ 
        PRAGMA table_info(results)
        """

pd.read_sql(query, conn)

    cid             name     type  notnull dflt_value  pk
0     0         resultId  INTEGER        0       None   0
1     1           raceId  INTEGER        0       None   0
2     2         driverId  INTEGER        0       None   0
3     3    constructorId  INTEGER        0       None   0
4     4           number     TEXT        0       None   0
5     5             grid  INTEGER        0       None   0
6     6         position     TEXT        0       None   0
7     7     positionText     TEXT        0       None   0
8     8    positionOrder  INTEGER        0       None   0
9     9           points     REAL        0       None   0
10   10             laps  INTEGER        0       None   0
11   11             time     TEXT        0       None   0
12   12     milliseconds     TEXT        0       None   0
13   13       fastestLap     TEXT        0       None   0
14   14             rank     TEXT        0       None   0
15   15   fastestLapTime     TEXT        0       None   0
16   16  fastestLapSpeed     TEXT        0       None   0
17   17         statusId  INTEGER        0       None   0

In [21]:
pd.read_sql("SELECT * FROM results LIMIT 5", conn)

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1

In [22]:
query = """ 
        SELECT COUNT(*) AS total, COUNT(DISTINCT resultId)
        FROM results
        """

pd.read_sql(query, conn)

   total  COUNT(DISTINCT resultId)
0  26759                     26759

In [23]:
query = """ 
        SELECT *
        FROM results
        WHERE resultId is NULL
        """

pd.read_sql(query, conn)

Empty DataFrame
Columns: [resultId, raceId, driverId, constructorId, number, grid, position, positionText, positionOrder, points, laps, time, milliseconds, fastestLap, rank, fastestLapTime, fastestLapSpeed, statusId]
Index: []

### relations between tables

In [24]:
# Does every result have a driver record in a drivers table
query = """ 
        SELECT resultId
        FROM results
        WHERE driverId not in (SELECT driverId from drivers)
        """

pd.read_sql(query, conn)

Empty DataFrame
Columns: [resultId]
Index: []

In [25]:
# How many drivers have more than one result record?
query = """ 
        SELECT COUNT(*) FROM (
            SELECT driverId
            FROM results
            GROUP BY driverId
            HAVING COUNT(*)>1
        )
        """

pd.read_sql(query, conn)

   COUNT(*)
0       687

In [26]:
# Does any driver have no result record?
query = """ 
        SELECT driverId 
        FROM drivers
        WHERE driverId not in (SELECT driverId FROM results)
        """

pd.read_sql(query, conn)

Empty DataFrame
Columns: [driverId]
Index: []

Thus, the drivers–results relationship is one-to-many:
- Each driver has one or more results (minimum: 1, maximum: many)
- Each result belongs to exactly one driver (minimum: 1, maximum: 1)

In [27]:
# Does every result have a constructor record in a constructors table
query = """ 
        SELECT resultId
        FROM results
        WHERE constructorId not in (SELECT constructorId from results)
        """

pd.read_sql(query, conn)

Empty DataFrame
Columns: [resultId]
Index: []

In [28]:
# How many constructors have more than one result record?
query = """ 
        SELECT COUNT(*) FROM (
            SELECT constructorId
            FROM results
            GROUP BY constructorId
            HAVING COUNT(*)>1
        )
        """

pd.read_sql(query, conn)

   COUNT(*)
0       179

In [29]:
# Does any constructor have no result record?
query = """ 
        SELECT constructorId
        FROM constructors
        WHERE constructorId not in (SELECT constructorId FROM constructors)
        """

pd.read_sql(query, conn)

Empty DataFrame
Columns: [constructorId]
Index: []

Thus, the constructors–results relationship is one-to-many:
- Each constructor has one or more results (minimum: 1, maximum: many)
- Each result belongs to exactly one constructor (minimum: 1, maximum: 1)

In [30]:
# Does every result have a races record in a races table
query = """ 
        SELECT resultId
        FROM results
        WHERE raceId not in (SELECT raceId from races)
        """

pd.read_sql(query, conn)

Empty DataFrame
Columns: [resultId]
Index: []

In [31]:
# How many races have more than one result record?
query = """ 
        SELECT COUNT(*) FROM (
            SELECT raceId
            FROM results
            GROUP BY raceId
            HAVING COUNT(*)>1
        )
        """

pd.read_sql(query, conn)

   COUNT(*)
0      1125

In [32]:
# Does any race have no result record?
query = """ 
        SELECT raceId
        FROM races
        WHERE raceId not in (SELECT raceId FROM results)
        """

pd.read_sql(query, conn)

Empty DataFrame
Columns: [raceId]
Index: []

Thus, the races–results relationship is one-to-many:
- Each race has one or more results (minimum: 1, maximum: many)
- Each result belongs to exactly one race (minimum: 1, maximum: 1)

In [33]:
# Does every race have a circuit record in a circuits table
query = """ 
        SELECT circuitId
        FROM races
        WHERE circuitId not in (SELECT circuitId from circuits)
        """

pd.read_sql(query, conn)

Empty DataFrame
Columns: [circuitId]
Index: []

In [34]:
# How many circuits have more than one races record?
query = """ 
        SELECT COUNT(*) FROM (
            SELECT circuitId
            FROM races
            GROUP BY circuitId
            HAVING COUNT(*)>1
        )
        """

pd.read_sql(query, conn)

   COUNT(*)
0        66

In [35]:
# Does any circuit have no race record?
query = """ 
        SELECT circuitId
        FROM circuits
        WHERE circuitId not in (SELECT circuitId FROM races)
        """

pd.read_sql(query, conn)

Empty DataFrame
Columns: [circuitId]
Index: []

Thus, the circuits–races relationship is one-to-many:
- Each circuit has one or more races (minimum: 1, maximum: many)
- Each race takes place at exactly one circuit (minimum: 1, maximum: 1)